### ISSUE TITLE
[Suggestion]: Config option to enable retraining on NPCs with experience.

### ISSUE THREAD

**Issue by JENOVAAbsolute** [Mrbysco/Retraining#1]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Villagers unlock new trades as they level up. What if you spend time recycling trades, finally get something decent, only for the trades you unlock later to be terrible. At that point, you've wasted your time, and have to repeat the process with a new villager.

**Comment by Mrbysco** [comment]
A config option has been added in the 1.21.8 version
