### ISSUE TITLE
[Bug]: The retraining button isn't showing

### ISSUE THREAD

**Issue by luffanji** [Mrbysco/Retraining#2]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

fabric-loader-1.19.2

### Mod version

1.2.0

### Java version

java 17

### Issue Description

Whenever I load into the game and try to retrain a villager the button doesn't appear. It just shows the standard gui.

**Comment by Mrbysco** [comment]
Have you ever traded with that villager? If so it won't show

**Comment by luffanji** [comment]
> Have you ever traded with that villager? If so it won't show

No I haven't its a fresh villager

**Comment by luffanji** [comment]
> 

I even tried breeding a whole new villager and giving it a job. Still didn't show up

**Comment by luffanji** [comment]
> 

I only have fabric api and retraining in the mods folder and it still wont work

**Comment by Mrbysco** [comment]
I'm unable to reproduce your issue.
I created a fresh install with just the fabric api and Retraining and I'm able to see the button just fine
![image](https://user-images.githubusercontent.com/9308260/212423653-d2ecb6f1-5406-4ed5-bb79-bdff0b89ada0.png)

**Comment by jukfiuune** [comment]
I also have the same problem - Java 17, Minecraft 1.19.2, fresh install - only Fabric API and Retraining Mod.

**Comment by Mrbysco** [comment]
Logs?

**Comment by luffanji** [comment]
> 

?

**Comment by Mrbysco** [comment]
In your minecraft instance there should be a logs folder, I need to see the latest.log to confirm the mod is even installed

**Comment by Mrbysco** [comment]
As I'm unable to reproduce your issue

**Comment by greggh** [comment]
Same situation for me, the button does not show up.

Edit:
I'm an idiot. This mod needs to be installed on the server AND the client at the same time to work. It works great now.

**Comment by Mrbysco** [comment]
Oh yeah, be sure that the server has the mod installed, otherwise it won't work. As you can't reset the trades on the client-side
